### ISSUE TITLE
Best way to save CrawledPage in JSON Format 

### ISSUE THREAD

**Issue by LeMoussel** [sjdirect/abot#100]
In `ProcessPageCrawlCompleted` event, I want to save `crawledPage` in NoSQL database in JSON format.
If I do 
````C#
private static void crawler_ProcessPageCrawlCompleted(object p_Sender, PageCrawlCompletedArgs p_PageCrawlCompletedArgs)
{
            CrawledPage crawledPage = p_PageCrawlCompletedArgs.CrawledPage;
            string json = Newtonsoft.Json.JsonConvert.SerializeObject(crawledPage );
}
````
I got some errors like 
````
{"Self referencing loop detected for property 'OwnerDocument' with type 'HtmlAgilityPack.HtmlDocument'. Path 'HtmlDocument.DocumentNode.ChildNodes[0].NextSibling.NextSibling.Attributes[0]'."}
````
To not have an error, I did this
````C#
private static void crawler_ProcessPageCrawlCompleted(object p_Sender, PageCrawlCompletedArgs p_PageCrawlCompletedArgs)
{
            CrawledPage crawledPage = p_PageCrawlCompletedArgs.CrawledPage;
            PageToCrawl pageCrawl = new PageToCrawl { Uri = p_PageCrawlCompletedArgs.CrawledPage.Uri,
                                                      IsRoot = p_PageCrawlCompletedArgs.CrawledPage.IsRoot,
                                                      IsInternal = p_PageCrawlCompletedArgs.CrawledPage.IsInternal,
                                                      CrawlDepth = p_PageCrawlCompletedArgs.CrawledPage.CrawlDepth,
                                                      PageBag = p_PageCrawlCompletedArgs.CrawledPage.PageBag,
                                                      RedirectedFrom = p_PageCrawlCompletedArgs.CrawledPage.RedirectedFrom,
                                                      RedirectPosition = p_PageCrawlCompletedArgs.CrawledPage.RedirectPosition
                                                    };
            string json = Newtonsoft.Json.JsonConvert.SerializeObject(pageCrawl );
}
````
but some crawledPage properties are not save in NoSQL DB..
Is there a way to ignore some properties such as `HtmlDocument` using the Json.NET serializer?

**Comment by mikegron** [comment]
Yes, try this: http://www.newtonsoft.com/json/help/html/t_newtonsoft_json_jsonignoreattribute.htm

[JsonIgnore]
public string MyProp { get; set; }

**Comment by LeMoussel** [comment]
Well .... If I understand, I must do a class inherits of CrawledPage with adding JsonIgnoreAttribute on properties to always skip writing it to the JSON result.

**Comment by mikegron** [comment]
You are right, but the property HtmlDocument is not virtual. I think it should be added to Abot, since I'm pretty sure we never want to serialize the HtmlDocument and CQ document anyway, you could add the  Ignore attribute to the CrawledPage's properties where it makes sense (not sure about web request/response)

**Comment by mikegron** [comment]
You could also write your own Json Serializer and use this, but it requires a little more code: http://blog.maskalik.com/asp-net/json-net-implement-custom-serialization/

**Comment by sjdirect** [comment]
I'm not sure I want to add a json specific attribute to the CrawledPage. What if someone wants to do binary, xml, or serialization? I think it would be a better idea for you to create your own custom object (even if it closely matches CrawledPage) that only has the fields you want to serialize.
