### ISSUE TITLE
Clean Url func in HyperLink parser

### ISSUE THREAD

**Issue by mikegron** [sjdirect/abot#101]
I've found a slight problem with the HapHyperlinkParser. In the constructor you can pass a Func to clean the urls extracted from the pages (cleanURLFunc), however, it is only applied the the link found in the DOM, and not the actual resulting absolute Url. Is there a reason for that?

Here is my use case. A web page `http://someWebSite.com/Home/Account` has relative links in the html like this: `<a href="../../About">`. Normally, this Url is resolved to `http://someWebSite.com/About`, however, the `../../About` string is passed to the "cleanURLFunc" (in the GetLinks method).

Is this expected? If not, I would just move the func in the GetUris method where the relative Url is appended to the base Url. Maybe adding a similar `Func<Uri, Uri>` in the base HyperlinkParser would make sense too?
Thanks!

**Comment by sjdirect** [comment]
I can see why your suggestion would make that functionality more useful. I'll leave this open so I can fix this in the future. Thanks!
