### ISSUE TITLE
Continue to use a patched version of html agility pack?

### ISSUE THREAD

**Issue by LeMoussel** [sjdirect/abot#103]
In [Issue 77](https://code.google.com/p/abot/issues/detail?id=77&can=1&q=htmlagilitypack) you say 
*Turns out that using HtmlDocument.OptionFixNestedTags = true solves this issue without needing the patched version.*
But if I install HAP V 1.4.9 via Nuget,  I got compil error in `InitializeHtmlAgilityPackDocument()` 
Line `hapDoc.OptionMaxNestedChildNodes = 5000;//did not make this an externally configurable property since it is really an internal issue to hap`
Does replace this line by `hapDoc.OptionFixNestedTags = true;`?

**Comment by sjdirect** [comment]
I'm not sure what I was talking about at the end of the post. I still use the patched version in Abot and AbotX because the last time I checked, ~8 months ago, my patch was still needed. Not sure what I was trying to say or if it was a mistake.
