### ISSUE TITLE
Crawl async possibility?

### ISSUE THREAD

**Issue by LeMoussel** [sjdirect/abot#105]
How can I do asynchronous crawl?

I found [AsyncWebCrawler ](https://github.com/sjdirect/abot/blob/06f91c589ad08e815c3ef1cf2a984c15eb55745c/Abot/Crawler/AsyncWebCrawler.cs#L12) class, but that does not seem to be completed.

Thanks for your help.

**Comment by sjdirect** [comment]
Can you use the forum for questions like this please? I want to be sure that others can benefit from questions like this. I notice most people don't look in the issues for questions like this.
