### ISSUE TITLE
If stoped - wait all events to be handled

### ISSUE THREAD

**Issue by Konard** [sjdirect/abot#109]
I made a webcrawler experiment here: https://github.com/Konard/LinksPlatform/tree/webcrawlerserver

And found a problem, if we ask to stop an abot (PoliteWebCrawler) it just stops all its threads, or waits for its threads, but it does not wait for events to be finished (for example crawler_ProcessPageCrawlCompleted).

Because of this it is required to keep a track of each thread that is involved in events handling like this:

``` C#
        private void crawler_ProcessPageCrawlCompleted(object sender, PageCrawlCompletedArgs e)
        {
            if (!Program.Threads.Contains(Thread.CurrentThread))
                Program.Threads.Add(Thread.CurrentThread);
...
```

And after this wait them all (Join), to correctly release resources, close connection to database, close the application itself & etc.

Is there is a better way to this? Or is it possible to integrate that feature into abot?

**Comment by sjdirect** [comment]
Can you give a more complete example of how/when you are trying to stop the crawl?

**Comment by Konard** [comment]
https://github.com/Konard/LinksPlatform/blob/c7b3c9ac12a2c2416ab8db100e670af8e1749b3c/Platform/Platform.Data.CrawlerServer/Crawler.cs

**Comment by sjdirect** [comment]
Does it work if you change...

crawler.PageCrawlCompletedAsync += crawler_ProcessPageCrawlCompleted;

to... 

crawler.PageCrawlCompleted += crawler_ProcessPageCrawlCompleted;

**Comment by Konard** [comment]
WOW, I didn`t notice this. I`ll check it.

**Comment by sjdirect** [comment]
Did that help you?

**Comment by Konard** [comment]
Looks like a better solution (if I decide not to use async events). Sync events are working ok (no need to track threads anymore). But if async events are required (for example to maximize CPU utilization) this issue still not solved.

**Comment by sjdirect** [comment]
I agree that it is an issue that needs to be fixed. Just wanted to be sure
it is what it appears to be.

Thanks

**Comment by sjdirect** [comment]
Async events have been removed with the release of abot 2.0.
