### ISSUE TITLE
Crawling http://www.example.com/ using PoliteWebCrawler does fire PageLinksCrawlDisallowedAsync event with reason Page has no content

### ISSUE THREAD

**Issue by maxpa1n87** [sjdirect/abot#112]
Hi, 

I just installed Abot from NuGet did a quik test code:

```
using System;
using Abot.Crawler;
using Abot.Poco;

namespace WebCrawler
{
	public class Program
	{
		public static void Main(string[] args) {
			try
			{
				var crawlConfig = new CrawlConfiguration();
				crawlConfig.CrawlTimeoutSeconds = 500;
				var webCrawler = new PoliteWebCrawler (crawlConfig);
				webCrawler.PageCrawlCompletedAsync += (object sender, Abot.Crawler.PageCrawlCompletedArgs e) => 
				{
					Console.Out.WriteLine("Crawling completed " + e.CrawledPage.Uri);
				};
				webCrawler.PageCrawlDisallowedAsync += (object sender, Abot.Crawler.PageCrawlDisallowedArgs e) => 
				{
					Console.Out.WriteLine("Crawling disallowed for " + e.PageToCrawl.Uri + " reason " + e.DisallowedReason);
				};
				webCrawler.PageCrawlStartingAsync += (object sender, Abot.Crawler.PageCrawlStartingArgs e) => 
				{
					Console.Out.WriteLine("Crawling starting for " + e.PageToCrawl.Uri);
				};
				webCrawler.PageLinksCrawlDisallowedAsync += (object sender, Abot.Crawler.PageLinksCrawlDisallowedArgs e) => 
				{
					Console.Out.WriteLine("Crawling links disallowed " + e.CrawledPage.Uri + " reason " + e.DisallowedReason);
				};
				webCrawler.Crawl (new Uri(args [0]));
			} catch(Exception e) {
				Console.Error.WriteLine ("Exception occured " + e.GetType ().Name + " message " + e.Message);
			}
		}
	}
}
```

Output is:
```
Crawling starting for http://www.example.com/
Crawling links disallowed http://www.example.com/ reason Page has no content
Crawling completed http://www.example.com
```
I would assume an output like crawling at least 1 link, because the page has 1 link.
Any idea why this test code is showing me the output shown above?

**Comment by sjdirect** [comment]
By default Abot ignores links that are external to the root uri. Try this...

var crawlConfig = new CrawlConfiguration { 
  IsExternalPageCrawlingEnabled = true, 
  IsExternalPageLinksCrawlingEnabled = false};

Now it will crawl links that are considered external to the site you are crawling but it will ignore links on external sites.

**Comment by sjdirect** [comment]
And if you are not happy with the how Abot determines if a uri is considered to be internal or external you can override it by passing in your own delegate...

webCrawler.IsInternalUri((uriInQuestion, ootUri) => uriInQuestion.Authority == rootUri.Authority);

**Comment by maxpa1n87** [comment]
Hi, I tried your settings but it still does not crawl any further than the uri itself. Maybe I'am doing it wrong. I don't know, here is the code I added to the above:

```
var crawlConfig = new CrawlConfiguration();
crawlConfig.CrawlTimeoutSeconds = 500;
crawlConfig.IsExternalPageCrawlingEnabled = true;
crawlConfig.IsExternalPageLinksCrawlingEnabled = false;

var webCrawler = new PoliteWebCrawler (crawlConfig);
```

and at the end I call...

`webCrawler.Crawl (new Uri("http://www.example.com/"));`

The output remains the same:

> Crawling starting for http://www.example.com/
> Crawling links disallowed http://www.example.com/ reason Page has no content
> Crawling completed http://www.example.com/

**Comment by mikegron** [comment]
www.example.com is a reserved domain. Try crawling another site like http://httpbin.org.
If you try to create an HttpWebRequest for www.example.com for instance, you will have this error (at least on my end) : `The remote name could not be resolved: 'www.example.com' `
The link on example.com redirects here: http://www.iana.org/domains/reserved, check it out!

**Comment by sjdirect** [comment]
You are going to have to turn on the log4net logging
<https://github.com/sjdirect/abot#logging-optional> to see whats happening
during your crawl. Those logs give you much better visibility into whats
going on.

**Comment by maxpa1n87** [comment]
Thanks for the response. I'll give it a try and see what the logs say.
