### ISSUE TITLE
Virtual methods in base classes

### ISSUE THREAD

**Issue by vovikdrg** [sjdirect/abot#113]
Why methods in base classes are not virtual for instance in CompactCrawledUrlRepository  i need override just 1 method ToMd5Bytes(string p_String) (yes its also static) but now i need to copy/paste and change just one line to make crawler case insensetive

**Comment by mikegron** [comment]
I don't think there is any reason, but feel free to mark them as virtual :)
However, if you need the crawler to be case-insensitive, why not apply a ToLower in the Hyperlink parser's "CleanUrlFunc"? This way you would be working with "case-insensitive" urls from the beginning.

**Comment by vovikdrg** [comment]
well in my case its a bit specific :) i need to crawl url as i found (since some times on linux case is important) so first link i found this will be used and other will be ignored. 
I dont know if it make sense :)
So if i found first link like "domain.com/Url" and then "domain.com/url" i should crawl only first one and other urls which are the same just different case should be ignored

**Comment by sjdirect** [comment]
I agree those should be more easily overridable. [Latest checkin](https://github.com/sjdirect/abot/commit/aaaf127c5bc3549ce0f55c3d312bdf1c86c14d61) should make all private/static methods protected and instance level. Next time feel free to submit a pull request. Nuget version > 1.5.0.153 should have this fix.
