### ISSUE TITLE
Abot Proxy Error

### ISSUE THREAD

**Issue by ashok-kr** [sjdirect/abot#114]
Hello,

I implemented ProxyPageRequester as suggested on this page - https://groups.google.com/forum/#!topic/abot-web-crawler/aD6Q5L8zYxE

However, sometimes this below line of code throws null reference exception - see screenshot - http://i.imgur.com/1icWUua.png

`HttpWebRequest request = base.BuildRequestObject(uri);`

Any solution/suggestion for this?

Regards,
Ashok

**Comment by sjdirect** [comment]
Can you please post the full PageRequester (and any other relevant code) that you have and how you are instantiating it and passing it into the PoliteWebCrawler constructor? Others are unlikely to dig through that thread to see what code you are referring to.

Also is it only that url in the screenshot that is triggering the error or is it random?

**Comment by ashok-kr** [comment]
This issue is random for any URLs. Below is the code for Proxy Page Requester Class - 

```
public class ProxyPageRequester : PageRequester
{
	public WebProxy Proxy { get; set; }
	public ProxyPageRequester(CrawlConfiguration crawlConfig)
		: base(crawlConfig)
	{
	}

	public ProxyPageRequester(CrawlConfiguration crawlConfig, IWebContentExtractor contentExtractor)
		: base(crawlConfig, contentExtractor)
	{
	}

	public ProxyPageRequester(CrawlConfiguration crawlConfig, WebProxy proxy)
		: this(crawlConfig)
	{
		this.Proxy = proxy;
	}

	protected override HttpWebRequest BuildRequestObject(Uri uri)
	{
		HttpWebRequest request = base.BuildRequestObject(uri);
		if (Proxy != null)
		{
			request.Proxy = Proxy;
		}
		return request;
	}
}
```

And I am using this class as follows - 

`var crawler = new PoliteWebCrawler(crawlConfig, null, null, null, new ProxyPageRequester(crawlConfig, proxy), null, null, null, null);`

Thanks for the update.

**Comment by sjdirect** [comment]
I spent some time trying to reproduce this error but was unsuccessful. Are you able to reproduce this regularly? Can you create a console app with all your code and settings along with a list of sites that would likely reproduce the issue?

**Comment by sjdirect** [comment]
Closing issue due to lack of response from reporter.
