### ISSUE TITLE
WebCrawler ShouldDownloadPageContentWrapper name

### ISSUE THREAD

**Issue by vovikdrg** [sjdirect/abot#115]
Hi guys,
i am wondering why method name is ShouldDownloadPageContentWrapper and not just ShouldDownloadPageContent as you have ShouldSchedulePageLink ?

**Comment by vovikdrg** [comment]
I can make pull request to fix that if there is no any reason for current naming

**Comment by sjdirect** [comment]
I renamed it. Thanks
