### ISSUE TITLE
Port to .NET Core

### ISSUE THREAD

**Issue by Konard** [sjdirect/abot#119]
Do you have any plans to make abot compatible with new .NET Core? So the NuGet package will work not only for ".NET Framework" but also for ".NET Platform".

**Comment by sjdirect** [comment]
No plans yet being its .net core is so new. It might be a while since all the dependencies would also need to be compatible before Abot could be. I'll leave this open so its on the radar.

**Comment by acastaner** [comment]
Would definitively support that feature. Running a crawler natively on Linux would be very, very interesting.

**Comment by thomasht** [comment]
With .NET Core having been released this seems like an appropriate time for implementing this. It is much needed.

**Comment by sjdirect** [comment]
Like I mentioned, this will likely not happen for a while. Obviously its a time/resource thing. I'm open to pull requests if someone wants to get started. 

High level we need to do...

-Fork to another repo for the .net core version of Abot
-Either replace or upgrade those dependencies that do not have support in .net core
-Rewrite Abot code works and doesn't work in .net core

**Comment by wesamco** [comment]
it's not as hard as you think it is. 
HtmlAgilityPack has been ported to .Net Core
what are you doing that you think will not work on .Net Core? I don't think there's anything.

**Comment by sjdirect** [comment]
I have create the [abot-dotnet-core](https://github.com/sjdirect/abot-dotnet-core) project and started the process of upgrading to .net core. I do not have time to complete this project. I'm looking for someone who can lead the porting efforts including setting up build server build with nuget package creation (like Abot has). I will give that person access as a contributer after a few pull requests demonstrate they know what they are doing.

**Comment by mfuzailzubari** [comment]
That is great. I will try to participate in this.

Thanks,

**Comment by toburger** [comment]
Are you sure this works at runtime?
The fact that a .NET framework library can be referenced on .NET Core doesn't mean that it runs on .NET Core.

At least I wasn't able to get it to run, but if you can share some guidance on how to configure the project I would be very pleased.

I get the following Exception when trying to run a simple crawl:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Abot.Crawler.WebCrawler' threw an exception. ---> System.MissingMethodException: Method not found: 'log4net.ILog log4net.LogManager.GetLogger(System.String)'.
   at Abot.Crawler.WebCrawler..cctor()
   --- End of inner exception stack trace ---
   at Abot.Crawler.WebCrawler..ctor(CrawlConfiguration crawlConfiguration, ICrawlDecisionMaker crawlDecisionMaker, IThreadManager threadManager, IScheduler scheduler, IPageRequester pageRequester, IHyperLinkParser hyperLinkParser, IMemoryManager memoryManager)
   at Abot.Crawler.PoliteWebCrawler..ctor(CrawlConfiguration crawlConfiguration, ICrawlDecisionMaker crawlDecisionMaker, IThreadManager threadManager, IScheduler scheduler, IPageRequester pageRequester, IHyperLinkParser hyperLinkParser, IMemoryManager memoryManager, IDomainRateLimiter domainRateLimiter, IRobotsDotTextFinder robotsDotTextFinder)
   at Abot.Crawler.PoliteWebCrawler..ctor()
   at abotcoretest.Program.Main(String[] args) in C:\work\abotcoretest\Program.cs:line 9
```
