### ISSUE TITLE
PoliteCrawler should have RobotsTxtCrawled event

### ISSUE THREAD

**Issue by vovikdrg** [sjdirect/abot#121]
One of the features of PoliteCrawler is to parse and respect robots.txt, its actually doing pretty cool. In addition robots txt can hold links to sitemaps and some other information which actually i need when i am crawling.

I have access only to IRobotsDotText encapsulate IRobots so to get sitemaps i need to do one more request to robots.txt and do some copy paste from base class, yes its not very consuming operation but why to do so when core functionality is doing pretty cool.

So my suggestion is to extend PoliteCrawler and add event RobotsTxtParsed which will path IRobots object, then i would be able in elegant way to read sitemaps and what ever i need from robots txt.

I can do PR but i need kind of approve of my idea.

**Comment by sjdirect** [comment]
This sounds like a reasonable approach. I would add the RobotsDotTextParseCompleted event to the PoliteWebCrawler and it looks like its time for a new interface called IPoliteWebCrawler. Feel free to submit a pull request otherwise I'll leave this open so I can add it in the future.

**Comment by vovikdrg** [comment]
Ok then i will do pull request during this week

**Comment by sjdirect** [comment]
@vovikdrg, Do you still plan on doing this?

**Comment by vovikdrg** [comment]
Yes i will try to find time this week

**Comment by sjdirect** [comment]
This was completed and is available since https://github.com/sjdirect/abot/pull/131
