### ISSUE TITLE
Enhancement: pass Xpath back with found links

### ISSUE THREAD

**Issue by MossP** [sjdirect/abot#128]
Sometimes one may want to block or crawl an url based on more than just the url itself. It would be useful to know where the link was in the markup and any classes/ids that make up that path. This would mainly be for `shouldCrawlPage()` but I guess would be useful in other places too.

Or make the source of the parent page available in `crawlContext` so the legwork could be done in custom code.

...Or am i looking in the wrong place?

**Comment by sjdirect** [comment]
Hi, I would then suggest creating your own IHyperlinkParser and only
include the links that are useful for that implementation. Given that there
may be many ways to get links from a page (css selectors, regex, stack
implementations) the context around the link has no common denominator
other than the link itself.

For example someone once asked how to get links from a sitemap.xml file. I
just suggested that they create a SiteMapHyperlinkParser.cs file and plug
it in.

**Comment by MossP** [comment]
Ah, fair point. That makes sense. I'll look into to that route instead then. Thank you for the component and thank you for replying.
