### ISSUE TITLE
Additional information: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by simonsattin** [sjdirect/abot#129]
Using version 1.4.9.0 and get the above exception when calling HtmlEntity.DeEntitize on the below text (i pasted the exact HTML but Github has decoded it into the characters e.g the black dots/bullets)

----REMOVED------

**Comment by IDisposable** [comment]
Strangest way I've ever seem to job-spam.

**Comment by sjdirect** [comment]
agreed. closing

**Comment by simonsattin** [comment]
hello. most definitely not job spam. i am attempting to crawl that website for data in the form of vacancies. When using HtmlEntity.DeEntitize with that text in my original comment it was throwing the above exception, not sure which characters in particular was the problem.

**Comment by sjdirect** [comment]
Sorry, can you re-add the stack trace and any other relevant data please?

**Comment by sjdirect** [comment]
Closing issue, not enough information to look into it. Also appears to be an issue with HtmlAgilityPack which is out of scope of this product.
