### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by vovikdrg** [sjdirect/abot#132]
Why its taking header encoding first and not meta tag?

**Comment by sjdirect** [comment]
Several sources state that the http header has precedence over the page level meta tag. Take a quick look [here](https://www.w3.org/International/questions/qa-html-encoding-declarations.en) and search for the word "precedence" on the page. I'll leave this issue open for a while to see if anyone has a strong argument to make a change.

**Comment by vovikdrg** [comment]
The bigest problem no body read that... Usually developer dont understand what they are doing. After 2 years of crawling various websites i dont believe in any standards.

**Comment by sjdirect** [comment]
I agree that many don't follow standards but I try to adhere where I can. You can easily override the WebContentExtractor.GetContent virtual method and just reorder them to whatever order you like. Interested if others will weigh in on this.

**Comment by vovikdrg** [comment]
Yes that is why i ask for a reason. For now probably lets leave it since good argument that i can point customer to the standards.
