### ISSUE TITLE
will you support javascript?

### ISSUE THREAD

**Issue by coldicelion** [sjdirect/abot#134]
hi, It's not support to execute javascript right now ? May you have any plan to support javascript later? thanks!

**Comment by sjdirect** [comment]
Abot does not support javascript rendering. AbotX <https://abotx.org/> (a
commercial extension to Abot) does offer javascript rendering
<https://abotx.org/Learn/JavascriptRendering>.

**Comment by sjdirect** [comment]
Abot does not support javascript rendering. [AbotX](https://abotx.org/) (a
commercial extension to Abot) does offer [javascript rendering](https://abotx.org/Learn/JavascriptRendering).

**Comment by coldicelion** [comment]
@sjdirect thanks,i'll get to know it.
