### ISSUE TITLE
Method not found: 'AutoMapper.IMappingExpression`2<!!0,!!1> AutoMapper.Mapper.CreateMap()'."

### ISSUE THREAD

**Issue by MaitlandMarshallMEX** [sjdirect/abot#138]
this.crawlConfig = new CrawlConfiguration();
            this.crawlConfig.CrawlTimeoutSeconds = 0;
            this.crawlConfig.IsExternalPageCrawlingEnabled = false;
            this.crawlConfig.MaxPagesToCrawl = int.MaxValue;
            this.crawlConfig.IsRespectRobotsDotTextEnabled = false;

            this.crawlConfig.MaxConcurrentThreads = this.MaxThreads;

            this.crawler = new PoliteWebCrawler(this.crawlConfig);
            this.crawler.PageCrawlCompleted += Crawler_PageCrawlCompleted;
            this.crawler.ShouldScheduleLink(Crawler_ShouldScheduleLink);

            this.waiter = new ManualResetEvent(false);

            this.cancelToken = new CancellationTokenSource();
            CrawlResult result = this.crawler.Crawl(new Uri("http://www.realpointitaly.com/"), this.cancelToken);

Error occurs immediately. This only occurs on the latest version of Abot. I have the latest version of AutoMapper too.

**Comment by sjdirect** [comment]
Did you figure out the issue?

**Comment by MaitlandMarshallMEX** [comment]
For some reason when nuget upgraded the Abot package, it also upgraded the AutoMapper package but didn't set the correct version numbers in the app.config.

**Comment by arisliang** [comment]
So whats the fix? I had the same issue.

**Comment by MaitlandMarshallMEX** [comment]
Make sure the version number in the app.config is the same as the AutoMapper dll.

If that doesn't work, try reinstalling Abot through Nuget,

**Comment by arisliang** [comment]
Thanks, that worked. Though abot is still using pretty old version of automapper.

**Comment by kgbuddhima** [comment]
I had this issue with v 8.0.0 and then I downgraded to v 7.0.1 and the application built without errors.

**Comment by cmozbas** [comment]
I had the same issue with version v8.1.0 using with Identity Server 4. I installed the version v8.0.0 and it worked fine.
