### ISSUE TITLE
Abot not compatible with newer versions of AutoMapper

### ISSUE THREAD

**Issue by sjdirect** [sjdirect/abot#142]
self explanitory

**Comment by terasato** [comment]
+1

**Comment by mlemanczyk** [comment]
+1

**Comment by sjdirect** [comment]
Newer versions of automapper require .net 4.5 which would force me to upgrade Abot's minimum required platform to .net 4.5. I removed its dependency on AutoMapper all together with the following...  https://github.com/sjdirect/abot/pull/153
