### ISSUE TITLE
Abot not compatible with the latest version of log4net.

### ISSUE THREAD

**Issue by terasato** [sjdirect/abot#143]
On initializing PoliteWebCrawler, it throws TypeInitializationException.

> {"ファイルまたはアセンブリ 'log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a'、またはその依存関係の 1 つが読み込めませんでした。見つかったアセンブリのマニフェスト定義はアセンブリ参照に一致しません。 (HRESULT からの例外:0x80131040)":"log4net, Version=1.2.15.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a"}

It says "found manifest definition does not match assembly reference".

log4net version 1.2.15.0 is no more available on NuGet (only 2.x and 1.2.10 are available), so it should be updated.

**Comment by sjdirect** [comment]
I'm not seeing any references to log4net 1.2.15.0 in the Abot project. I just see a reference to 2.0.3.

<package id="log4net" version="2.0.3" targetFramework="net40" />

**Comment by sjdirect** [comment]
Closing this issue. Must being using a very old version of Abot or the user's project that references Abot has assembly binding redirects that are causing issues.
