### ISSUE TITLE
Can I sort methods?

### ISSUE THREAD

**Issue by terasato** [sjdirect/abot#144]
Hi,
I am trying to make a pull request that updates NUnit package to 3.5.0.
I am using ReSharper to boost my development and it sorts methods by default.
Is there any problem if I sort (test) methods?
And if you already have ReSharper settings file, please add it to the repository.
Thanks in advance.

**Comment by sjdirect** [comment]
Hi, I prefer to not have the tests sorted since sometimes they are logically grouped. I use all the default settings on resharper. Thanks!

**Comment by terasato** [comment]
OK:+1:
