### ISSUE TITLE
Feature request - crawling predefined urls

### ISSUE THREAD

**Issue by ShadowDancer** [sjdirect/abot#147]
Hello.
I use abot a lot for website integration tests and SEO tests (check if everything in sitemap returns 200, check if site is up after deploy, etc.). If you see such feature in I would gladly contribute.

**Comment by sjdirect** [comment]
Hi, those sound like very useful features but I'm not sure it would be useful enough to the common abot user to justify having it in Abot source. Any way to develop it as a seperate product that extends abot? Something like "Abot-SEO"?

**Comment by ShadowDancer** [comment]
The only problem with separate project is that, I need access to scheduler before crawling starts, so I need to (?) subclass crawler (I am doing so in my private implementation). This would be a problem in public library I guess?

**Comment by sjdirect** [comment]
This wouldn't work for you?

var scheduler = new Scheduler();
var crawler = new PoliteWebCrawler(null, ..., scheduler, ...);
crawler.Crawl(new Uri("blah"));

**Comment by ShadowDancer** [comment]
It does, thanks a lot! If you are interested I may link my repo here when I am done.

**Comment by sjdirect** [comment]
Yes please do. Always want to see what cool products/features people build using abot
