### ISSUE TITLE
HtmlAgilityPack dependency removed?

### ISSUE THREAD

**Issue by madebysoren** [sjdirect/abot#149]
Hi @sjdirect,

We get the following error when crawling pages with a MaxDepth > 0. But isn't HAP supposed to be removed as a dependency in favor of AngleSharp?

Field not found: 'HtmlAgilityPack.HtmlDocument.OptionMaxNestedChildNodes'.

   at Abot.Poco.CrawledPage.InitializeHtmlAgilityPackDocument()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Abot.Core.HapHyperLinkParser.GetHrefValues(CrawledPage crawledPage)
   at Abot.Core.HyperLinkParser.GetLinks(CrawledPage crawledPage)
   at Abot.Crawler.WebCrawler.ParsePageLinks(CrawledPage crawledPage)
   at Abot.Crawler.WebCrawler.ProcessPage(PageToCrawl pageToCrawl)

**Comment by sjdirect** [comment]
It will be in the future. However, now the default is still HapHyperlinkParser. You can override this by passing in an instance of AngleSharpHyperlinkParser to the crawler constructor then you wont have to worry about it. Otherwise, the OptionMaxNestedChildNodes is a property that only exists in a patched version that I created to solve a problem with HAP. I suspect you are also somehow referencing the HAP version from a nuget package which would not have the OptionMaxNestedChildNodes property.

**Comment by madebysoren** [comment]
Seems like a good add-on. I might look into that. In the meantime I checked whether we were referencing HAP from NuGet and we are not. We have been using it in other projects, but replaced it with AngleSharp. However there might have been some legacy dll's that wasn't cleaned properly. I've tried to clean up and remove all of those, but now I get this:

{"Could not load file or assembly 'HtmlAgilityPack, Version=1.4.9.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' or one of its dependencies. The system cannot find the file specified.":"HtmlAgilityPack, Version=1.4.9.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a"}

I can see HtmlAgilityPack.dll in the packages\Abot.1.5.1.53\lib\net40 folder, however it is not copied to the bin/Debug folder when building.

**Comment by madebysoren** [comment]
Hi again @sjdirect,

I now initialize the crawler like this:

```
_crawler = new CrawlerX(_config, new ImplementationContainer
            {
                HyperlinkParser = new AngleSharpHyperlinkParser()
            });
```
However I still get the following error:

{"Could not load file or assembly 'HtmlAgilityPack, Version=1.4.9.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a' or one of its dependencies. The system cannot find the file specified.":"HtmlAgilityPack, Version=1.4.9.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a"}

I then installed HAP through NuGet and now it works usings the AngleSharpHyperlinkParser. I highly recommend making this the default in future updates. Good job!
