### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by fzzzt** [sjdirect/abot#150]
I've been trying to use this library to test loading a site but I am getting very different results than my browser. I am trying to basically mimic what a browser would download, but this (supposedly) downloads five times the data in five times the time. Instead of ~1MB in ~4sec (browser) it says ~5MB in ~25sec.

	Stopwatch sw = new Stopwatch();
	sw.Start();
	CrawlConfiguration cc = new CrawlConfiguration {
		CrawlTimeoutSeconds = 30,
		MaxCrawlDepth = 1,
		MaxConcurrentThreads = 10,
		IsRespectRobotsDotTextEnabled = false,
		DownloadableContentTypes = "text/plain,text/html,text/javascript,application/javascript,image/jpeg,image/gif,image/png"
	};
	PoliteWebCrawler pwc = new PoliteWebCrawler(cc);
	pwc.PageCrawlCompleted += (s, a) => { contentLength += a.CrawledPage.Content.Bytes.Length; };
	pwc.Crawl(new Uri(config.url));
	sw.Stop();

What am I doing wrong? Could it be parallelism, or a problem with depth, or both, or...?

**Comment by sjdirect** [comment]
Abot does not impersonate a browser so it is likely that the server is responding differently to crawler requests. Try a tool like Screaming Frog (another crawler) and see what it gets. Wish I had more for you. To many variables to determine what it could be.
