### ISSUE TITLE
Disallow all pages with question mark. 

### ISSUE THREAD

**Issue by Jawoch** [sjdirect/abot#154]
Hi ,

I'm using your library in one of my projects, and I have to admit I truly love it! 

However at one point my client decided to add “Disallow: /*?” statement in robots and from this point my problems starts. Google recommend this as best practice to block all url with question mark in it. I've already find out nRobots is trimming question marks from the end of statements (I don't know why but I'm not relay familiar with robots and crawling). 

So the question is, do you have any solution form that problem? Is it any way to make it work as google says or some other statement that covers this requirement?

**Comment by azhagananbu** [comment]
![anders_hejlsberg](https://cloud.githubusercontent.com/assets/27333355/24999286/91b4f948-205a-11e7-9ca3-ba9171988038.jpg)

**Comment by sjdirect** [comment]
The [NRobots](https://github.com/sjdirect/nrobots) project that Abot relies on does not support that condition. A work around is to set...

isIgnoreRobotsDotTextIfRootDisallowedEnabled=true

which will ignore robots.txt if it determines the instruction is the block the entire site.
