### ISSUE TITLE
How to Use Abot to get specific product details from an online shop 

### ISSUE THREAD

**Issue by Nazmerit** [sjdirect/abot#157]
Please, I Want to crawl online shops for products details like price and description .
How can I use Abot to get specific product details from an online shop?

**Comment by eigil-rosager** [comment]
Use Abot (which is f... fantastic) to load pages from the site(s). Use RegExp to search for the specific information that you need. Optionally check the URL for each page that is about to be crawled and stop if it is a page you don't need.
