### ISSUE TITLE
CrawledPage URI same as Parent URI 

### ISSUE THREAD

**Issue by tombro32** [sjdirect/abot#158]
Not sure if this is a bug or I have something misconfigured.  I downloaded the master branch and ran the demo project. No matter what domain I crawl, every crawled page reports the parent url the same as the url of the page itself...

I've attached a sample log file.

[abotlog.txt](https://github.com/sjdirect/abot/files/882825/abotlog.txt)

**Comment by sjdirect** [comment]
This is a bug. Thanks for reporting. Stand by for hot fix hopefully today.

**Comment by sjdirect** [comment]
Nuget version Abot.1.5.1.69 solves this issue

**Comment by tombro32** [comment]
Excellent; thanks for the fast turnaround.
