### ISSUE TITLE
OptionFixNestedTags = false fixes nested issue

### ISSUE THREAD

**Issue by maozoomd** [sjdirect/abot#159]
Latest version of HtmlAgilityPack has OptionFixNestedTags property in HtmlDocument (Defines if LI, TR, TH, TD tags must be partially fixed when nesting errors are detected. Default is false).
Setting this property to 'true' instead of _hapDoc.OptionMaxNestedChildNodes = 5000;_ enables abot to work with the latest version.

I suggest enabling this option in config if user doesn't care about nesting errors.

**Comment by sjdirect** [comment]
Hello, I've tried multiple times over the years to see if the latest html agility pack version solves the specific problem that I patched. All of them did not. I will accept a pull request if whatever nuget package version passes all unit tests and specifically...

CrawledPageTests.cs:
HtmlDocument_ToManyNestedTagsInSource1_DoesNotCauseStackOverflowException
HtmlDocument_ToManyNestedTagsInSource2_DoesNotCauseStackOverflowException
CsQueryDocument_ToManyNestedTagsInSource1_DoesNotCauseStackOverflowException
CsQueryDocument_ToManyNestedTagsInSource2_DoesNotCauseStackOverflowException
