### ISSUE TITLE
Can I cancel the page crawl in PageCrawlStartingAsync event?

### ISSUE THREAD

**Issue by YodasMyDad** [sjdirect/abot#166]
I have some specific rules and checks on the Url that I do during crawling the site. And there are occasions where I want to cancel a page crawl based on the url. 

Can I cancel just this page crawl in the PageCrawlStartingAsync event? So it basically skips the page and carries on?

**Comment by luisabreu** [comment]
I'm under the impression that you need to use one of the methods explained on the Customize the crawl behavior section...

**Comment by Ruffio** [comment]
@YodasMyDad can this be closed?
