### ISSUE TITLE
Number of pages to crawl

### ISSUE THREAD

**Issue by fatagun** [sjdirect/abot#170]
Hello, 

What is the best way to crawl a website without defining number of pages to be crawled?

Since I dont know, or dont have an estimate on the number of pages to be crawled, I can't define anything. 

How should I tell the crawler to crawl all the site? Also, I don't want the crawler to go to external domain. 

Thanks.

**Comment by San-Jeevan** [comment]
number of pages to crawl = 0 (infinite)

**Comment by Ruffio** [comment]
@fatagun can this be closed?

**Comment by fatagun** [comment]
Yes. Thanks.
