### ISSUE TITLE
Allow seeding the crawler with a list of URLs to crawl

### ISSUE THREAD

**Issue by khaledh** [sjdirect/abot#18]
I need to crawl a site multiple times to get updated content on a regular basis.

In order to save on bandwidth and avoid unnecessary work, I have customized the `PageRequester` class by deriving from it so that I can add an If-Modified-Since header to only request pages that have been modified since the last crawl. (I know I could have just  added a delegate for `ShouldDownloadPageContent` to make the decision, it's much cleaner to use HTTP headers to tell the server not to send the response if the page wasn't modified, than to let the server send the response but have the crawler ignore it).

The problem I'm having is that let's say the root page wasn't modified. In this case it's not going to be fetched and no links will ever be scheduled for crawling. This is going to stop the crawl immediately.

My request is to allow the crawler to be seeded with a list of URLs to crawl. In the first crawl session, I'm going to supply only the root Uri. In each subsequent crawl session I'm going to supply all URLs that have been crawled before for scheduling. This should allow the crawler to continue crawling those links even if any page containing those links isn't crawled due to not being modified.

When I looked I found that if I get access to the Scheduler object on the `CrawlContext` I can schedule those links. But the problem is that the `CrawlContext` is not available before starting the crawl; it's only passed when events/delegates are raised/invoked. I can certainly try to inherit from `WebCrawler` (or `PoliteWebCrawler`) and expose the context/scheduler or a method to seed the crawler with a list of URLs.

I guess my request is either:
1) Expose the `CrawlContext` on the `IWebCrawler` interface,
2) Expose the `IScheduler` interface through the `IWebCrawler` interface (doesn't feel right), or
3) Add an override to the `IWebCrawler.Crawl()` method that takes `IEnumerable<Uri>`

**Comment by sangamu** [comment]
Hi khaledh, I am also trying to feed list of Uris to the crawler so that I can benefit from the scheduling feature. Could you illustrate how you scheduled the list of urls yourself in your derived crawler class? Thank you.
