### ISSUE TITLE
Is there any way to pass context from the Crawler invocation to the PageCrawlCompletedAsync method?

### ISSUE THREAD

**Issue by tudorserbanconnatix** [sjdirect/abot#181]
I can user ConfigurationExtensions but that's a Dictionary<string, string> and thus a bit awkward. My current solution is to pass a key to a global Dictionary of context objects that the PageCrawlCompletedAsync cand then retrieve. Is there a better, built-in way, to do this?

**Comment by sjdirect** [comment]
Please post questions like this in the [user forum](https://groups.google.com/forum/#!forum/abot-web-crawler).
