### ISSUE TITLE
On MacOS it's not possible to build this project

### ISSUE THREAD

**Issue by SabiKi** [sjdirect/abot#183]
I worked with Visual Studio for Mac. 
This Project is not possible to build on my device, I think the reason is the different parameters for the cmd and terminal on Windows or MacOS.

`Error MSB3073: The command "mono --runtime=v4.0.30319 /Users/../abot/.nuget/NuGet.exe install "packages.config" -source ""   -RequireConsent -solutionDir "/Users/../abot/ " " exited with code 1. (MSB3073) `

Did anyone have the same problem?

Thanks for your help.

**Comment by sjdirect** [comment]
Just created new projects that will replace the. Net 4.0 Target builds. This will likely be resolved soon when I remove the older projects.
