### ISSUE TITLE
Is AbotX supported on .NET Core?

### ISSUE THREAD

**Issue by tudorserbanconnatix** [sjdirect/abot#189]
Or is only the basic version ported to .NET Core?

**Comment by sjdirect** [comment]
Hello, 
AbotX is not currently supported on .net core. That may change in the near future but no active development is happening at the moment.

**Comment by sjdirect** [comment]
Abot now targets .NET standard 2.0. I'm planning on porting AbotX as well so then it will be supported on .net core.

**Comment by sjdirect** [comment]
AbotX now targets .net standard 2!!!
