### ISSUE TITLE
HtmlAgilityPack Assembly Version

### ISSUE THREAD

**Issue by paulbackhouse** [sjdirect/abot#192]
Point 1
HtmlAgilityPack isn't listed as an Abot dependency and it is.

Point 2
HtmlAgillityPack Version 1.4.7 is not longer available via nuget which Abot has a dependency on

Can you upgrade the Abot dependency to latest HtmlAgilityPack please.

**Comment by sjdirect** [comment]
I cannot. See issue #21 for the details. High level, there is a patched version of html agility pack that is used for a good reason. There are unit tests that prove/exercise it. There have been at least 4-5 github issues created where people are requesting what you are asking but every time i investigate it, the same problem persists.

**Comment by sjdirect** [comment]
Reopening this so people see the issue and do not create another ticket unless they have addressed by original concerns.

**Comment by sjdirect** [comment]
Hap is no longer a dependency since version 2.0.
