### ISSUE TITLE
Status on dotnet standard and dotnet core support 

### ISSUE THREAD

**Issue by silashansen** [sjdirect/abot#200]
I see you have created a new branch for dotnet standard. 

What is the status of your work there? Is abot expected to be compatible with dotnet core anytime soon? 

I'm sorry if I've missed if you already mentioned this somewhere, but I have not been able to find any comments on the work you've done on this branch

Thank you for a great piece of software.

**Comment by sjdirect** [comment]
Hi Silas,

Yes, planning on chipping away at the the dotnet standard branch. It will be a while before I have something that is prime time ready. As, I get closer to a stable version I'll begin communicating to you all. Glad you like using Abot. Hoping to get this version out and tested this year.

**Comment by silashansen** [comment]
That sounds really good :-)
Are you facing any specific challenges at the moment that you'd like to share with us?

**Comment by sjdirect** [comment]
Just lack of time/priority :)

**Comment by sjdirect** [comment]
.net standard now supported with version 2.0 and beyond!
