### ISSUE TITLE
Library does not work when link crawled is very slow

### ISSUE THREAD

**Issue by sbonello** [sjdirect/abot#203]
When the library is used on a link that is very slow the work threads count goes to zero and the threadmanager closes as there wasn't enough time for the links to be scheduled. 

The delay added to wait for the list to be built is not enough

 Log.Debug("Waiting for links to be scheduled...");
 await Task.Delay(2500).ConfigureAwait(false);

**Comment by erherhh4herh** [comment]
Can confirm, this abot2 just does not work at all... Recommend you stick with abot1 💯

**Comment by sjdirect** [comment]
Can you give me a some examples sites/pages please?

**Comment by sbonello** [comment]
http://zalahat.com

Is an example. I have more.

**Comment by sjdirect** [comment]
Appreciate it. Yes a few more world be helpful as well.

**Comment by sbonello** [comment]
gamble1x2.com
casinosms.pl
centrodeapostas.com

Anything slower than 3 seconds will not be parsed.

**Comment by sjdirect** [comment]
Instead of just waiting longer I reverted back to the old way of blocking the thread with Thread.Sleep.

**Comment by sjdirect** [comment]
@sbonello @erherhh4herh Can you both verify this has been fixed?

**Comment by sbonello** [comment]
Nope same issue. If the site takes longer than 2.5 seconds to load it will
not be parsed.

Simon

**Comment by sjdirect** [comment]
Am able to reproduce and have a fix i'm still testing. Bear with me, hopefully i can polish it up tomorrow.

**Comment by sjdirect** [comment]
I believe I fixed the issue. Even added some integration tests to make sure Zalahat is crawled correctly. The latest nuget package (2.0.46) should be up to date. Please verify whether it works or does not for you.

**Comment by sjdirect** [comment]
Assuming the silence means its working as expected.
