### ISSUE TITLE
Can't install package in VS 2017

### ISSUE THREAD

**Issue by MESWEB** [sjdirect/abot#205]
> Error		Could not install package 'Abot 2.0.47'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by sjdirect** [comment]
You are trying to install a dotnet standard 2 project into a project that targets .net 4.5. If you project targets .net 4.6.1 or greater it should work. If you can't change the target of your project you can just install abot nuget versions less than 2.0 and you should be good.
