### ISSUE TITLE
Abot Crawler Cancellation Not Working As Per README.md

### ISSUE THREAD

**Issue by RadwanRadoo** [sjdirect/abot#206]
`using Abot2.Crawler;
using Abot2.Poco;
using NUglify;
using Serilog;
using SODExtraction.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using TikaOnDotNet.TextExtraction;

namespace SODExtraction
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public static string UrlWords { get; set; }

        public static long PageCount { get; set; }
        public static long PageCompleted { get; set; }
        public static long PageSuccess { get; set; }
        public static long PageException { get; set; }

        CancellationTokenSource cancellationTokenSource;

        public MainWindow()
        {
            InitializeComponent();

            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .WriteTo.Console()
                .CreateLogger();

            Log.Logger.Information("Demo starting up!");

            onlineSearchResults = new List<OnlineSearchResult>();

            PageCount = 0;
            PageCompleted = 0;
            PageSuccess = 0;
            PageException = 0;
        }

        private void LeftSideBarMenuList_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            int index = LeftSideBarMenuList.SelectedIndex;

            switch (index)
            {
                case 0:
                    if (GridAdvancedSearch != null)
                        GridAdvancedSearch.Visibility = Visibility.Visible;
                    if (GridUpdateDatabase != null)
                        GridUpdateDatabase.Visibility = Visibility.Collapsed;
                    if (GridSearchHistory != null)
                        GridSearchHistory.Visibility = Visibility.Collapsed;

                    MoveCursorMenu(0);

                    break;
                case 1:
                    GridAdvancedSearch.Visibility = Visibility.Collapsed;
                    GridUpdateDatabase.Visibility = Visibility.Visible;
                    GridSearchHistory.Visibility = Visibility.Collapsed;

                    MoveCursorMenu(1);

                    break;

                case 2:
                    GridAdvancedSearch.Visibility = Visibility.Collapsed;
                    GridUpdateDatabase.Visibility = Visibility.Collapsed;
                    GridUpdateDatabase.Visibility = Visibility.Visible;

                    MoveCursorMenu(2);

                    break;

                default:
                    GridAdvancedSearch.Visibility = Visibility.Visible;
                    GridAdvancedSearch.Visibility = Visibility.Collapsed;
                    GridUpdateDatabase.Visibility = Visibility.Collapsed;

                    MoveCursorMenu(0);
                    break;
            }
        }

        private void MoveCursorMenu(int index)
        {
            TrainsitionigContentSlide.OnApplyTemplate();
            GridCursor.Margin = new Thickness(0, (50 * index), 0, 0);
        }

        private async void BtnSearch_Click(object sender, RoutedEventArgs e)
        {

            if (BtnSearch.Content.ToString() == "Search")
            {
                PageCount++;

                UrlWords = TxtboxUrlWords.Text;

                var config = new CrawlConfiguration
                {
                    MaxPagesToCrawl = int.MaxValue,
                    UserAgentString = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36",
                    MaxCrawlDepth = int.Parse(TxtboxMaxCrawlDepth.Text),
                    MinCrawlDelayPerDomainMilliSeconds = 3000
                };

                var crawler = new PoliteWebCrawler(config);

                crawler.PageCrawlCompleted += PageCrawlCompleted;
                crawler.ShouldCrawlPageDecisionMaker += ShouldCrawlPageDecisionMaker;

                cancellationTokenSource = new CancellationTokenSource();
                BtnSearch.Content = "Cancel";

                var crawlResult = await crawler.CrawlAsync(new Uri(TxtboxUrl.Text), cancellationTokenSource);
            }
            else
            {
                try
                {
                    cancellationTokenSource.Cancel();
                    BtnSearch.Content = "Search";
                }
                catch (OperationCanceledException ex)
                {
                }
            }
        }

        private CrawlDecision ShouldCrawlPageDecisionMaker(PageToCrawl arg1, CrawlContext arg2)
        {
            CrawlDecision ret = new CrawlDecision();

            bool check = false;
            foreach (var word in UrlWords.Split(';').ToArray())
                if (arg1.Uri.AbsoluteUri.Contains(word))
                    check = true;

            if (check == false)
            {
                ret.Allow = false;
                return ret;
            }
            else
            {
                ret.Allow = true;
                return ret;
            }
        }

        private void PageCrawlCompleted(object sender, PageCrawlCompletedArgs e)
        {
            PageCompleted++;

            if (e.CrawledPage.HttpRequestException != null || e.CrawledPage.HttpResponseMessage.StatusCode != HttpStatusCode.OK)
            {
                PageException++;
                return;
            }

            PageSuccess++;

            if(e.CrawledPage.ParsedLinks != null)
            {
                PageCount += e.CrawledPage.ParsedLinks.Count();
            }
        }
    }
}
`

I am trying to count pages that have specific words in the url.
when the crawler is working, i need to cancel it with all it's threads so i used the CancellationTokenSource as per README.md in you github https://github.com/sjdirect/abot

`CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();

var crawler = new PoliteWebCrawler();
var result = await crawler.CrawlAsync(new Uri("addurihere"), cancellationTokenSource);`

but it does not working! it throw exception 
"System.OperationCanceledException: 'The operation was canceled.'" attached picture.

https://ibb.co/HXVQ5wC

**Comment by sjdirect** [comment]
You should be able to  F5 past that. Abot will catch that exception and stop the crawl as expected. You can see the integration test below that exercises this code. Also check your logs for a message like "Crawl cancellation requested for site".

```
[TestMethod]
public async Task Crawl_Synchronous_CancellationTokenCancelled_StopsCrawl()
{
	var cancellationTokenSource = new CancellationTokenSource();
	var timer = new System.Timers.Timer(800);
	timer.Elapsed += (o, e) =>
	{
		cancellationTokenSource.Cancel();
		timer.Stop();
		timer.Dispose();
	};
	timer.Start();

	var crawler = new PoliteWebCrawler();
	var result = await crawler.CrawlAsync(new Uri("http://localhost.fiddler:1111/"), cancellationTokenSource);

	Assert.IsTrue(result.ErrorOccurred);
	Assert.IsTrue(result.ErrorException is OperationCanceledException);
}
```

**Comment by BogdanGrytsko** [comment]
WebCrawler gets calcelled but it also crashed the application. "End" is never executed. See the attached screenshot        
static void Main(string[] args)
        {
            Crawl().Wait();
            Thread.Sleep(10 * 1000);
            Console.WriteLine("End");
            //DoWork().Wait();
        }
        private static async Task Crawl()
        {
            try
            {
                var tokenSource = new CancellationTokenSource();
                var crawler = new PoliteWebCrawler(GetConfig());
                crawler.PageCrawlCompleted += CrawlerOnPageCrawlCompleted;
                tokenSource.CancelAfter(TimeSpan.FromSeconds(15));
                var x = await crawler.CrawlAsync(new Uri("https://www.getter-tech.co.il/"), tokenSource);
                //Thread.Sleep(TimeSpan.FromSeconds(15));
                //Console.WriteLine("Cancelled");

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
        private static CrawlConfiguration GetConfig()
        {
            var crawlConfig = new CrawlConfiguration
            {
                CrawlTimeoutSeconds = 60,
                MaxRetryCount = 3,
                MaxPagesToCrawl = 1000,
                MaxPagesToCrawlPerDomain = 1000,
                MaxCrawlDepth = int.MaxValue,
                MaxLinksPerPage = int.MaxValue,
                MinRetryDelayInMilliseconds = 750,
                MinCrawlDelayPerDomainMilliSeconds = 250,
                //UserAgentString = SystemWebRequestInvoker.UserAgentRandom,
                //RobotsDotTextUserAgentString = SystemWebRequestInvoker.UserAgentRandom,
                IsHttpRequestAutoRedirectsEnabled = true,
                IsHttpRequestAutomaticDecompressionEnabled = true,
                IsRespectAnchorRelNoFollowEnabled = false,
                IsRespectMetaRobotsNoFollowEnabled = false,
                IsIgnoreRobotsDotTextIfRootDisallowedEnabled = true,
                IsRespectRobotsDotTextEnabled = false,
                IsSendingCookiesEnabled = true,
                IsSslCertificateValidationEnabled = false,
                IsRespectHttpXRobotsTagHeaderNoFollowEnabled = false,
                IsUriRecrawlingEnabled = false,
                // MaxConcurrentThreads = 1,
                // HttpRequestTimeoutInSeconds = 30,
            };
            return crawlConfig;
        }

![image](https://user-images.githubusercontent.com/16352538/114313350-d8868f80-9afe-11eb-8006-44d45711fac2.png)

**Comment by BogdanGrytsko** [comment]
I also used your example and got application crash. I think key to reproducing is giving bigger timeout before cancel(15 sec) and crawling heavier site.

        static void Main(string[] args)
        {
            ExampleCrawl().Wait();
            Thread.Sleep(10 * 1000);
            Console.WriteLine("End");
        }

        private static async Task ExampleCrawl()
        {
            try
            {
                var cancellationTokenSource = new CancellationTokenSource();
                var timer = new System.Timers.Timer(15 * 1000);
                timer.Elapsed += (o, e) =>
                {
                    cancellationTokenSource.Cancel();
                    timer.Stop();
                    timer.Dispose();
                };
                timer.Start();

                var crawler = new PoliteWebCrawler();
                var result = await crawler.CrawlAsync(new Uri("https://www.getter-tech.co.il/"), cancellationTokenSource);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

        }

**Comment by jgoodman8** [comment]
Any updates regarding this? I'm suffering from the same issue.
