### ISSUE TITLE
Abot as Static Site Generator

### ISSUE THREAD

**Issue by glikoz** [sjdirect/abot#210]
I want to convert my dynamic web site to static web site.  What is your opinion about that? Is "abot" is 
a good starting point to do this requirement.

**Comment by sjdirect** [comment]
Yes, I you can use Abot to do this if your pages are rendered by the server. If they are rendered by clientside javascript then you would need to use AbotX's js rendering capability. Either approach would just have to save the the fully rendered page to disk as an html file using the data in the e.CrawledPage.Content object that is accessible from the Abot/AbotX events.
