### ISSUE TITLE
Encoding not applied when getting content from response on Abot2

### ISSUE THREAD

**Issue by marcmarsinach** [sjdirect/abot#212]
On Abot2, the content from the response is obtained before resolving charset encoding. As a result, the content presents issues with special characters on none UTF8 charsets. For instance, getting content with charset windows-1252. At the meantime, I'm overwriting WebContentExtractor with the Abot implementation.

The trick in the classic Abot implementation was passing the encoding (e) to the StreamReader. This is not currently done in the Abot2 implementation:

`using (StreamReader sr = new StreamReader(memoryStream, e))`

**Comment by sjdirect** [comment]
Fixed in [nuget version 2.0.55](https://www.nuget.org/packages/Abot/2.0.55)
