### ISSUE TITLE
Subdomains links are treated as external links

### ISSUE THREAD

**Issue by marcmarsinach** [sjdirect/abot#213]
When crawling a page with links pointing to the same domain but with different subdomain, they are considered as external links and are excluded and not crawled. The only option is to enable IsExternalPageCrawlingEnabled, but it could be dangerous in some scenarios.

**Comment by sjdirect** [comment]
[This example](https://groups.google.com/forum/#%21searchin/abot-web-crawler/IsInternalUri/abot-web-crawler/EOdKQK0d_5U/KMuI53msTBgJ) demonstrates how to use the a delegate that can customize what is considered internal to the root domain. Let me know if that works for you.
