### ISSUE TITLE
How to implement the decision maker function

### ISSUE THREAD

**Issue by kunal0810** [sjdirect/abot#216]
I am working on project where before crawling a page i need to check whether should a crawl this page or not. i have tried using the shouldcrawlpagedecisionmaker and does not get the right way to implement that.

can someone please help to get it correct.
Displaying image.png
![image](https://user-images.githubusercontent.com/33775276/84473365-8f7b6a00-aca6-11ea-8bdb-d117fe2fb716.png)

**Comment by sjdirect** [comment]
Apologies, the doc snippet was using a no longer supported method. Switch it to a property instead as the example below. I also updated the readme doc.

```
crawler.ShouldCrawlPageDecisionMaker = (pageToCrawl, crawlContext) => 
{
	var decision = new CrawlDecision{ Allow = true };
	if(pageToCrawl.Uri.Authority == "google.com")
		return new CrawlDecision{ Allow = false, Reason = "Dont want to crawl google pages" };
	
	return decision;
};
```
