### ISSUE TITLE
Best way to do page-by-page crawling

### ISSUE THREAD

**Issue by okolobaxa** [sjdirect/abot#224]
Hello,

My source site structure looks so;
http://example.com/page/1
http://example.com/page/2 
and so on... But some pages may not contain what I'm looking for (images).

What is the most efficient way to crawl such a site with Abot?
For now, I use my own implementation of HyperLinkParser, which queues the next page by incrementing the URL of the current crawled page. Maybe there is a more efficient way? I'm thinking of my own implementation of Scheduler with pre-calculated URLs.

Thanks!

**Comment by sjdirect** [comment]
Are you asking how to crawl a site that has a predictable url structure but
the links are not discoverable by just following links the abot crawls or
are you asking how to avoid crawling pages that do not have images?

**Comment by sjdirect** [comment]
Closing issue, taking the conversation to the forum
