### ISSUE TITLE
Exception is thrown when redirect URI is relative

### ISSUE THREAD

**Issue by chjahnert** [sjdirect/abot#229]
The `WebCrawler.ExtractRedirectUri(...)` method may [get the redirect location](https://github.com/sjdirect/abot/blob/ccd9f6dc98fe1292a892519d6eadb7bdc1322dde/Abot2/Crawler/WebCrawler.cs#L929) from the `Location` header. If the value of the `Location` header is a relative URI, accessing the `AbsoluteUri` property throws an exception. Consider using either `ToString()` or `OriginalString` to get the URI.

**Comment by sjdirect** [comment]
fixed by https://github.com/sjdirect/abot/commit/62a2e3e8dc6a1c4753daf2003442f0767fe61ca4 and available in nuget 2.0.68
