### ISSUE TITLE
Base URI logic of the HyperLinkParser breaks on Linux when faced with a root-relative base tag value

### ISSUE THREAD

**Issue by thedeedawg** [sjdirect/abot#230]
### Description

The handling of root-relative URIs by the `Uri` ctor is platform dependent:

- When running on Windows, `/` is considered to be relative
- When running on Linux, `/` is considered to be absolute as it points to the root of the local filesystem

This is currently not taken into account by the base URI logic of the `HyperLinkParser`, and an assumption is made that the Windows behavior is the only behavior.

_A PR is in the works._

---

### Example  no. 1

1. The crawler crawls the page `https://www.mydomain.com/`
   - The following base tag is present on the page
     ```html
     <base href="/">
     ```
   - The following link is present on the page
     ```html
     <a href="subpage.html">Lorem ipsum dolor sit amet</a>
     ```
2. The `HyperLinkParser` returns the URI `file:///subpage.html`, but would be expected to have returned `https://www.mydomain.com/subpage.html` instead

### Example  no. 2

1. The crawler crawls the page `https://www.mydomain.com/`
   - The following base tag is present on the page
     ```html
     <base href="/pages">
     ```
   - The following link is present on the page
     ```html
     <a href="subpage.html">Lorem ipsum dolor sit amet</a>
     ```
2. The `HyperLinkParser` returns the URI `file:///subpage.html`, but would be expected to have returned `https://www.mydomain.com/subpage.html` instead

**Comment by sjdirect** [comment]
Is this handled [this pr](https://github.com/sjdirect/abot/pull/232) correctly?

**Comment by thedeedawg** [comment]
Yes, closing.
