### ISSUE TITLE
Abot is not able to crawl a password protected web site

### ISSUE THREAD

**Issue by ashwini47** [sjdirect/abot#37]
When we are trying to crawl password protected site (with basic authentication) crawler fails with message that page has no content.  Url That I am passing is http://username:password@siteurl

**Comment by ashwini47** [comment]
Hi Steven

My Apology for such a long delayed response, 
Due to some legal restriction I won`t be able to share fiddler log but 
Today I got some time to look into this  It seems that I got the issue 

ABOT is using HttpWebRequest that by default do not support url pattern like http://user:pw@mysite.com. In fact it does`t work even in IE by default without Registry hacks 

Here is what I tested 
Code var responce = HttpWebRequest.Create("http://username:password@mysite.com").GetResponse(); throws an 401 exception 

But when I passed basic authentication like below it works perfect 

 var credCache = new CredentialCache();
            credCache.Add(new Uri("http://mysite.com"), "Basic", new NetworkCredential("User", "Pw"));
   
            var request = HttpWebRequest.Create("http://mysite.com");
                 request.Credentials = credCache;
             var responce=request.GetResponse();

Then I looked ABOT source code and it seem there is not explicit support for  passing 401 credential 

Unfortunately I am not able to complile the code on may machine so not able to test so thought to let you know may be you can help 

regards
Ashwini

**Comment by sjdirect** [comment]
Reopening to consider a way to allow basic authentication through configuration.

**Comment by ashwini47** [comment]
Thanks for accepting as feature request , Let me know if I can contribute.

**Comment by Ruffio** [comment]
Hi. This feature will be much appreciated. If possible it should be made as a 'plugin' thereby allowing to develop other authentication methods such as federated login.

If I can help in testing this, please let me know.

**Comment by obender** [comment]
I will Implement basic authentication through configuration.

**Comment by Nesse** [comment]
I'm using authentication for crawling some specific websites. You can take a look at the following issue:
https://github.com/sjdirect/abot/issues/81

**Comment by obender** [comment]
Hi, 
I had done coding & implementing unit  tests, 
But when trying to commit I get 
remote: Permission to sjdirect/abot.git denied to obender.
fatal: unable to access 'https://github.com/sjdirect/abot.git/': The requested URL returned error: 403

**Comment by sjdirect** [comment]
Hi,  you can submit your changes through a pull request.

Steven

**Comment by obender** [comment]
Yes, but I need to commit & push the changes somewhere no ? (Sorry for the nubby questions, never contributed on GitHub, first time :-) )

Do i need to fork the project ?
Or there a branch that I can commit...

**Comment by sjdirect** [comment]
Yes you would need to fork then commit changes to your fork. Then you
submit a pull request from your repo to abots repo master branch.

Lots of tutorials online on how to do that.
Thanks

**Comment by obender** [comment]
Yes, 
No problem,

**Comment by sjdirect** [comment]
pull request above now allows basic authentication through config values

**Comment by zixiliuyue** [comment]
Thank you, I climbed over ten thousand more interesting links this afternoon. I don't need an account password. I see that the CrawledPage object has a HttpWebRequest property, which is set up in the PageCrawlCompleted event after the first request, CrawledPage.HttpWebRequest? I am a Chinese student, English is a bit bad, I hope to understand.... Thank you.0.0

**Comment by obender** [comment]
Didn't got your question.... 

Do you want to setup the request object on  PageCrawlCompleted event  ?

**Comment by zixiliuyue** [comment]
yes 0.0

**Comment by obender** [comment]
Why... ?
PageCrawlCompleted  it's after the request was done.

**Comment by zixiliuyue** [comment]
我犯迷糊了，对不起

**Comment by zixiliuyue** [comment]
我犯迷糊了，对不起
I am confused, sorry
