### ISSUE TITLE
Add pause, stop, resume

### ISSUE THREAD

**Issue by sjdirect** [sjdirect/abot#45]
Add functionality that will allow a crawl to be continued from where it was stopped or paused.

**Comment by sjdirect** [comment]
Made all classes in Abot project Serializable so others may implement a pause/resume

**Comment by sjdirect** [comment]
More talk about this here...
https://groups.google.com/forum/#!topic/abot-web-crawler/KiYhgjaESNU

**Comment by sjdirect** [comment]
this is on the abot trello board

**Comment by songshine** [comment]
When run the crawler with multi-threads, a exception will be throw if cancel the crawl operation.

**Comment by sjdirect** [comment]
Your comment is not relevant to this issue. Please create another issue but only if you are planning on giving a lot more information about the exception details.

**Comment by mnta** [comment]
Hi sjdirect, if you don't mind I ask, I remember you have a file based Url and Crawl repository in Google repository before, or is it my memory corrupted or fragmented. I hope I understand this issue correctly, but as long as Abot resume previous unfinished task, that will satisfy this ticket? i.e. stop / resume and pause is consider as stop. I am working on a simple Mongodb based Scheduler for Abot, I will upload to Github later, but then again, if you don't mind it is in F#. Thanks.

**Comment by sjdirect** [comment]
Yes there use to be a file based crawl repo but it was overly complex and under performant. A lightweight version of it MAY be created if I decide that is the best way to pause the crawl.

**Comment by mnta** [comment]
Hi Steven, I added a new repository using Redis as scheduler store (I thought about using MongoDB before, but Redis gives much better performance as it runs in memory). That should allow the crawler to start and stop without losing track of previous progress. Hope this will help. Cheers. https://github.com/mnta/Abot.Redis.Scheduler

**Comment by sjdirect** [comment]
Thanks, i'll take a look at this when I cross that bridge

**Comment by sjdirect** [comment]
You can use the Pause/Resume feature of [AbotX](https://abotx.org). AbotX build on top of abot. Closing issue.
