### ISSUE TITLE
Add a priority queue implementation for url scheduling

### ISSUE THREAD

**Issue by cjsheehan** [sjdirect/abot#52]
It would be great to have a priority queue implementing Abot.Core.IPagesToCrawlRepository, allowing url's to be prioritised dynamically.  There are generic .NET implementations of priority queues in the public domain (hopefully avoid reinventing the wheel) although there doesn't appear to be one in the .NET framework.

**Comment by cjsheehan** [comment]
https://github.com/Sinbadsoft/Sinbadsoft.Lib.Collections  has a priority queue that allows comparator injection.

**Comment by cjsheehan** [comment]
http://visualstudiomagazine.com/articles/2012/11/01/priority-queues-with-c.aspx has a nice implementation using a binary heap.

**Comment by sjdirect** [comment]
If you would like to contribute a solid implementation of IPagesToCrawlRepository using one of those I would be willing to add it to Abot. See https://code.google.com/p/abot/wiki/Contribute for instructions on how to contribute. In addition to any new tests that implementation would need to pass the Abot.Tests.Unit.Core.PagesToCrawlRepositoryTest.cs as well.

**Comment by sjdirect** [comment]
Will not be adding this since it is trivial for users to plug in their own IPagesToCrawlRepository to the existing code. Thanks!

**Comment by cjsheehan** [comment]
OK, fair enough.

Date: Mon, 16 Mar 2015 14:44:07 -0700
