### ISSUE TITLE
Include Abot.xml in NuGet package

### ISSUE THREAD

**Issue by jokedst** [sjdirect/abot#55]
Right now we don't get all the nice comments in the source code as intellisense documentation when using the NuGet package.

You should output the "XML documentation file" in the build of Abot and include the generated Abot.xml in the NuGet package

**Comment by sjdirect** [comment]
Thank you for the suggestion. Also please consider submitting a pull request. The nuspec file is in the Abot project csproject directory. Its invisible to visual studio.
