### ISSUE TITLE
Abot crawer is not working when IsRespectRobotsDotTextEnabled is set to True

### ISSUE THREAD

**Issue by MAK11** [sjdirect/abot#56]
Abot crawler is not crawling the website : http://www.percona.com when i set IsRespectRobotsDotTextEnabled = true in the configuration.
I even validated the robots.txt file of www.percona.com.

**Comment by sjdirect** [comment]
Looks like the the querystring portion is being taken of the directives and then blocking the whole site...

"/?blahblahblah" => "/"

**Comment by sjdirect** [comment]
This has been fixed, available in nuget 1.5.0.19

**Comment by MAK11** [comment]
@sjdirect Thanks :)
