### ISSUE TITLE
Add option to get charset of page from body which is enclosed by `'` character

### ISSUE THREAD

**Issue by supermartzin** [sjdirect/abot#58]
I noticed in [WebContentExtractor class](https://github.com/sjdirect/abot/blob/master/Abot/Core/WebContentExtractor.cs) of Abot Crawler, in `GetCharsetFromBody` method, that when it comes to parsing charset of page from page's body, it only counts with the case that `charset` attribute is enclosed in `"` characters.
For example this works and charset is correctly recognized:
```html
<meta http-equiv="Content-Type" content="text/html; charset=windows-1250" />
````

But in situation that `meta` tag uses `'` characters, for example
````html
<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
````
the charset is not correctly recognized and whole text later extracted from page contains weird characters. 

I suggest to edit following method, especially this part:
````c#
if (meta != null)
{
     int start_ind = meta.IndexOf("charset=");
     int end_ind = -1;
     if (start_ind != -1)
     {
            end_ind = meta.IndexOf("\"", start_ind);
            if (end_ind != -1)
            {
                   int start = start_ind + 8;
                   charset = meta.Substring(start, end_ind - start + 1);
                   charset = charset.TrimEnd(new Char[] { '>', '"' });
            }
     }
}
````
and change it to this:
````c#
if (meta != null)
{
     Match match = Regex.Match(meta, @"<meta.*charset=(.+)\/>");
     if (match.Success)
     {
          string match_str = match.Groups[1].Value;

          int end_ind = match_str.IndexOf('"');
          if (end_ind == -1)
               end_ind = match_str.IndexOf('\'');

          if (end_ind != -1)
               charset = match_str.Remove(end_ind);
     }
}
````
so now it will correctly recognize both cases of writing the `meta` tag.

**Comment by sjdirect** [comment]
Thanks for the contribution. The final solution was little more complex but it should make sense if you take a look.

**Comment by sjdirect** [comment]
nuget v1.5.0.71 has this fix

**Comment by supermartzin** [comment]
Thanks.
