### ISSUE TITLE
internal / external link detection  is wrong?

### ISSUE THREAD

**Issue by LeMoussel** [sjdirect/abot#59]
Function _isInternalDecisionMaker falsely detects that the link is external
```
protected Func<Uri, Uri, bool> _isInternalDecisionMaker = (uriInQuestion, rootUri) => uriInQuestion.Authority == rootUri.Authority;
```

EG :
http://docs.mysite.com/P1.html has a link such as http://www.mysite.com/
```
rootUri.Authority = docs.mysite.com
uriInQuestion.Authority = www.mysite.com
```
=> _isInternalDecisionMaker return False

Or is True because. docs or www are subdomains. www.mysite.com is internal.

To detect if link is internal or external, you can use [domainname-parser](https://github.com/danesparza/domainname-parser) lib.

**Comment by sjdirect** [comment]
This is the expected behavior due to them being different subdomains. You can override doing something like the solution described here...

https://groups.google.com/forum/#!searchin/abot-web-crawler/IsInternalUri/abot-web-crawler/EOdKQK0d_5U/KMuI53msTBgJ
