### ISSUE TITLE
Add canonical redirection

### ISSUE THREAD

**Issue by LeMoussel** [sjdirect/abot#64]
Abot detects canonical link element [#63 Add canonical to links found in a page](https://github.com/sjdirect/abot/pull/63) and has the [#61 Adding support for not automatic redirects](https://github.com/sjdirect/abot/pull/61).

Like Redirection, It may be interesting to add feature to crawl Canonical URL without losing the ability to get notifications via  `PageCrawlCompleted` even.

**Comment by xavivars** [comment]
Probably I didn't understand you properly, but if the automatic redirects are off, when a canonical returns a 301, you still get the notification via PageCrawlCompleted.

**Comment by LeMoussel** [comment]
Yes you are right.  But a canonical link is somewhat a redirection. 
So I was thinking about an option indicating that a canonical link is present on the page and get notification via PageCrawlCompleted even.

**Comment by xavivars** [comment]
And which URL should send the PageCrawlCompleted? The original one, or the canonical? Maybe, what could be added is a flag to CrawledPage that distinguished ParentUriTypes, having "link", "canonical", etc. But I don't see what else could be done.

**Comment by sjdirect** [comment]
I don't think there is a desirable way to handle a common use case since really it just depends on what your exact requirements are. Closing this request due to uncertainty on what would be useful the majority. Thanks!
