### ISSUE TITLE
Canhcel crawl job running with multi-threads will cause a exception threw

### ISSUE THREAD

**Issue by songshine** [sjdirect/abot#68]
When you cancel the crawl job, the WebCrawler will dispose the _threadManager and its _resetEvent will also be displsed. But the ThreadManager class can't make sure that all threads running have been completed at the time. So if a thread is running the RunAction method and it will catch a OperationCanceledException exception and finally _resetEvent.Set() will throw a exception said the safe handle was closed.

**Comment by sjdirect** [comment]
Thanks for submitting this
