### ISSUE TITLE
Q: Implementing page prefetching

### ISSUE THREAD

**Issue by clausavram** [sjdirect/abot#73]
What I mean to ask is: Is it possible to implement downloading of pages without marking them as visited yet?

A concrete use case for me is that I want to make the crawler more targeted, by checking if crawled pages are in a topic defined by some hand-picked documents.
Unimportant pages generally should not be crawled further, but in the case a relevant page is referenced by a less relevant one, it should not be missed.
The way I want to solve this is by taking all child pages up to a certain ***depth*** from the currently crawled document (resulting in a tree with the root the current page).
If none of the pages in the tree are relevant, all of them should be marked as visited and skip them, but if there are enough good items, crawl the whole tree.

How hard would it be to try to implement such a behavior in the crawlers current structure?

[Edit] After some research, found I should add functionality to PageRequester class

**Comment by sjdirect** [comment]
All that you describe can be done by implementing your own
ICrawlDecisionMaker implementation (CrawlDecisionMaker.cs is the default
impl). It makes all the decisions that would support your use case above. I
do think I should point out that to see what links are on a page or if a
page is defined in some hand picked document, it still needs to be crawled.
Looks like what you need to do is crawl everything but only process the
pages that meet your criteria. Either way the
ICrawlDecisionMaker/CrawlDecisionMaker is where you would do this.

Hope that helps
Steven

**Comment by clausavram** [comment]
I feel this is a very helpful tip and look into it.
Thank you,
Claudiu

**Comment by clausavram** [comment]
Hello,

I have started using you crawler and find it very nice.
I have though a persistent issue when trying to use HtmlAgilityPack in the
solution inside any project except *Abot* (while trying to use it for ex.
for tag querying inside Html pages).
The problem manifests as a version mismatch by not finding the binaries for
an older library version than the currently installed one.

I have seen that *Abot* has a functioning reference to HtmlAgilityPack
version 1.4.7 that does not appear in either NuGet or in Refereces Manager.
My presumption is that when I install HtmlAgilityPack into another project,
the old binary is overwritten with a newer version.
I tried installing the earlier version 1.4.7 manually through the console,
so I would use it in the new project as well, but that version sadly is not
available through NuGet.

If I install the newer version of HtmlAgilityPack 1.4.9 into *Abot* project,
I get compiler errors like:

> 'HtmlAgilityPack.HtmlDocument' does not contain a definition for
> 'OptionMaxNestedChildNodes' and no extension method
> 'OptionMaxNestedChildNodes' accepting a first argument of type
> 'HtmlAgilityPack.HtmlDocument' could be found (are you missing a using
> directive or an assembly reference?)


How can I make the solution work and still use HtmlAgilityPack in projects
other than *Abot*?

Your help would be greatly appreciated,
Claudiu Avram

**Comment by sjdirect** [comment]
Hi,

See if this helps you...

https://github.com/sjdirect/abot/issues/21

If that doesn't work, try uninstalling HAP from your application, then
install Abot, then reinstall your version of HAP. It may be smart enough to
handle the assembly binding redirects for you.

Hope that helps
Steven

**Comment by clausavram** [comment]
I have been trying to do some debugging and so want to look at the source code for HtmlAgilityPack (version 1.4.7).
As it's not an official version, how can I get the sources for version 1.4.7?

**Comment by sjdirect** [comment]
Source code here...

https://abot.googlecode.com/issues/attachment?aid=770004000&name=HapStackOverFlowPatch.zip&token=ABZ6GAeSqUptoYfLzcHQELllP68EgNK-TQ%3A1433539498630&id=77&mod_ts_token=ABZ6GAeutITp5b6fdz9wA4Z_izU7r3KbEg%3A1433539498630

**Comment by clausavram** [comment]
Thank you very much :)
