### ISSUE TITLE
Multithreaded with list of proxies and crawl delay

### ISSUE THREAD

**Issue by sirjimjones** [sjdirect/abot#74]
Hi,

I want ot crawl a certain website as fast as possible without getting banned.

My setup:
- List of proxies
- 20 threads
- 400ms crawl delay

Using proxies works fine but as the name implies the minCrawlDelayPerDomainMilliSeconds only applies to the domain.

It would be cool to have somthing to make a delay between every request using a proxy. You could run 20 threads and each thread makes the 400ms crawl delay.

**Comment by mnta** [comment]
I created a simple one on https://github.com/mnta/Abot.MultiProxyPoliteCrawler, that should cover your requirements. It's written in F# if you don't mind, I'm new to F# and Abot, and created this project as part of learning process. And there is no unit tests at the moment. Regards.

**Comment by sjdirect** [comment]
Thanks for providing your solution

**Comment by jimjonesGIT** [comment]
Thanks mnta for your F# solution. Has anyone successfully converted it to C# yet and wanna share the results?

**Comment by mnta** [comment]
I hope I can find the time this week or next to convert it to C#, it shouldn't be too much work I hope. But I don't think I have time to implement unit tests at this stage.

**Comment by mnta** [comment]
Add C# version of MultiProxyPoliteWebCrawler to https://github.com/mnta/Abot.MultiProxyPoliteWebCrawler

I will try to add testing and simple documentation when possible. Cheers.

**Comment by sjdirect** [comment]
Thanks! I'll try to find a way to get this in soon.

**Comment by mnta** [comment]
Thanks for the reply, take your time, I need to add unit testings and perform refactoring if possible. But my current schedule doesn't give me enough freedom to do so. Please let me know if you need anything. Cheers.

**Comment by sjdirect** [comment]
Time is the shortest resource I have as well. I will not likely get around
to this any time soon. I'll leave this open for others to use your solution.

Thanks

**Comment by sjdirect** [comment]
A bigger feature (called Block Avoidance) will do this in a much more advanced way. It is being built in another product called [AbotX](https://abotx.org). Closing the issue here.
