### ISSUE TITLE
GetCharsetFromHeaders() bug?

### ISSUE THREAD

**Issue by LeMoussel** [sjdirect/abot#76]
I think there must be a bug in GetCharsetFromHeaders() in  Abot/Core/WebContentExtractor.cs

Indeed, if there is something after the charset variable, the information will be taken.
```C#
int ind = ctype.IndexOf("charset=");
if (ind != -1) charset = ctype.Substring(ind + 8);
```

**Comment by sjdirect** [comment]
My understanding of the spec is that "charset" is optional and can follow any valid mime type. This is the common format that is encountered....

Content-Type: application/json; charset=UTF-8

Also outlined here http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17

Are you seeing other formats?

**Comment by LeMoussel** [comment]
Media types define in section [3.7](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7) of this RFC indicate
```
media-type     = type "/" subtype *( ";" parameter )
type           = token
subtype        = token
```
So if I understand correctly, there may be more parameters for type/subtype

**Comment by sjdirect** [comment]
Do you have specific examples of raw content-type values being returned that are not being parsed as you expect? Based on that spec I still believe the implementation is correct. The only place you can put parameters is when you have the...

type/subtype; charset=whatever

The other examples don't seem to allow other parameters.

**Comment by LeMoussel** [comment]
No I don't have specific examples of raw content-type values.
OK for your explications.
I propose to close this issue.

**Comment by sjdirect** [comment]
Thanks!
