### ISSUE TITLE
Following 301 redirects

### ISSUE THREAD

**Issue by fatagun** [sjdirect/abot#83]
Great project, I must say. Really cool stuff you have here. 

I have a question, there is URI I want to crawl as follows: http://www.foo.com , this www does 301 to http://foo.com , abot is not following 301 redirect for some reason.

In http://foo.com there are 640 links. But when i crawl http://www.foo.com, i get back 1 link.

Is there a config to get this done. 

My work around was parsing the URL and removing www.

**Comment by sjdirect** [comment]
These settings tell Abot to automatically follow redirects for you. It will
make the request and behind the scenes follow any redirects until it gets a
non redirect, then it will return that status and content as if the
original url returned it.

      httpRequestMaxAutoRedirects="7"
      isHttpRequestAutoRedirectsEnabled="true"


Hope that helps

**Comment by fatagun** [comment]
Thank you.
