### ISSUE TITLE
Parallel cluster support

### ISSUE THREAD

**Issue by fatagun** [sjdirect/abot#84]
Hey man,

This is a great project. I have tried other open source spiders but this is the best I have seen so far. 

A great feature would be to get it working in a cluster. ie. have 10 servers run in parallel. 

Anyhow, this is an awesome project. Big ups.

**Comment by sjdirect** [comment]
Thanks for the compliment. This would likely be another product if I were to implement it. Thanks for the suggestion.

**Comment by sjdirect** [comment]
This feature will likely end up in the [AbotX](https://abotx.org) project. Closing the issue here.
