### ISSUE TITLE
CrawlREsult does not return any data about the url

### ISSUE THREAD

**Issue by gomtimehta** [sjdirect/abot#86]
I am uisng the configuration that is specified in quick start
and my crawlresult "Yiled no reesult"
 CrawlConfiguration crawlConfig = new CrawlConfiguration
            {
                CrawlTimeoutSeconds = 100,
                MaxConcurrentThreads = 10,
                MaxPagesToCrawl = 5,
                UserAgentString = "abot v1.0 http://code.google.com/p/abot",
                
            };
            PoliteWebCrawler crawler = new PoliteWebCrawler(crawlConfig, null, null, null, null, null, null, null, null);

**Comment by sjdirect** [comment]
Abot does not keep the pages it crawled in memory. It just makes you aware of them one by one using the events covered in the quickstart documentation. Its up to you to save or keep track of them. This alleviates memory issues. Imagine a crawl of a site with a million pages, Abot could not just say "ok i'm done, here are a million pages in a list".
