### ISSUE TITLE
Feature: crawleable AJAX url 

### ISSUE THREAD

**Issue by LeMoussel** [sjdirect/abot#89]
Crawleable AJAX url according to: http://code.google.com/web/ajaxcrawling/docs/getting-started.html

For example : 
````
www.example.com/ajax.html#!key=value => www.example.com/ajax.html?_escaped_fragment_=key%3Dvalue
www.example.com/ajax.html?k1=v1&k2=v2#!key=value => www.example.com/ajax.html?k1=v1&k2=v2&_escaped_fragment_=key%3Dvalue
www.example.com/ajax.html?#!key=value => www.example.com/ajax.html?_escaped_fragment_=key%3Dvalue
www.example.com/ajax.html#! => www.example.com/ajax.html?_escaped_fragment_=
````
URLs that are not "AJAX crawlable" (according to Google) returned as-is:
````
www.example.com/ajax.html#key=value => www.example.com/ajax.html#key=value
www.example.com/ajax.html# => www.example.com/ajax.html#
www.example.com/ajax.html => www.example.com/ajax.html
````

**Comment by sjdirect** [comment]
This seems more like a protocol to follow on the server to make your ajax pages "indexable" by google. As long as the server responds when Abot makes requests with any of the formats above then the crawl should be good. I do not see any benefit to transforming the urls with "!" chars from Abot's point of view.

Thanks for bringing it up though. I'll leave this open for a while in case you or others have a compelling argument.
