### ISSUE TITLE
JavaScript Support with PhantomJS & IPC

### ISSUE THREAD

**Issue by LeMoussel** [sjdirect/abot#92]
I've created an extension (as described by sjdirect: https://github.com/sjdirect/abot/issues/91#issuecomment-146278245) using the headless browser PhantomJS  and manipulating it using Inter Process Communication (http://phantomjs.org/inter-process-communication.html).

I have a problem, in MakeRequest(...). It's necessary to Initialize HttpWebRequest else you got exception in HyperLinkParser.cs:ligne 83 (Uri uriToUse = crawledPage.HttpWebRequest.Address ?? crawledPage.Uri;)
```C#
        public virtual CrawledPage MakeRequest(Uri uri, Func<CrawledPage, CrawlDecision> shouldDownloadContent)
        {
            if (uri == null)
                throw new ArgumentNullException("uri");

            CrawledPage crawledPage = new CrawledPage(uri)
            {
                RequestStarted = DateTime.UtcNow,
                DownloadContentStarted = DateTime.UtcNow,
                HttpWebResponse = new HttpWebResponseWrapper(),
                // Initialize HttpWebRequest else you got exception in HyperLinkParser.cs:ligne 83 (Uri uriToUse = crawledPage.HttpWebRequest.Address ?? crawledPage.Uri;)
                HttpWebRequest = (HttpWebRequest)WebRequest.Create(uri)
            };
            .....
        }
```

**Comment by sjdirect** [comment]
I"m not understanding exactly what you need here. Why can't you just let the initialization of the WebRequest happen? Even if you dont use it for a real request (like if you use phantom to make it) it's still useful.
