### ISSUE TITLE
Compact Url Repository (reducing memory usage)

### ISSUE THREAD

**Issue by mikegron** [sjdirect/abot#98]
I have written a new Url repository using md5 hash to greatly reduce the amount of memory required. Basically it only keeps the hash value in the dictionary to know if an url is contained in it.

In my test, when adding 1 million urls of 150 chars length required around 350 Mo of ram. With this repository it only takes 30 Mo.
We calculated the odds of collisions to be 0.0002% after 100 millions entries, which seems acceptable.

Here: https://drive.google.com/file/d/0B1Cc-jmpA6imdGxLZWJJb1lVMFE/view?usp=sharing 
Tell me what you think!

**Comment by sjdirect** [comment]
Thanks for the contribution. I have added the CompactCrawledUrlRepository to Abot and it is now the default implemenation that is used by Scheduler.cs.
